name: Lifesteal
version: '${project.version}'
main: net.meadownetwork.lifesteal.main
api-version: 1.18
authors: [ Banker ]
commands:
  resethealth:
    usage: /resethealth
    description: Reset your max health to the default value of 20
  gm:
    usage: /<command>
    description: Toggle your gamemode
  fly:
    usage: /<command>
    description: Toggle your fly mode
  report:
    usage: /report <player>
    description: Report a player to the server staff
  rtp:
    usage: /rtp <player>
    description: Randomly teleport to a random possible location
  customheartgiver:
    usage: /<command>
    description: Give you a heart item
  maintenancemode:
    usage: /<command> <enable/disable>
    description: Toggle maintenance mode
  crategive:
    usage: /<command>
    description: Give you a crate
  vanish:
    usage: /<command>
    aliases:
      - v
    description: Toggle your vanish mode
  setspawn:
    usage: /setspawn
    description: sets the servers spawn point
  spawn:
    usage: /spawn
    description: Teleport you to spawn
  playerinfo:
    usage: /playerinfo <player>
    description: Get information about a player (ADMIN ONLY)
  discord:
    usage: /discord
    description: sends the player a discord link
  clearlag:
    usage: /clearlag
    description: Clears all entities from the world
  night:
    usage: /night
    description: Sets the time to night
  day:
    usage: /day
    description: Sets the time to day
  msg:
    usage: /msg <player> <message>
    aliases:
      - w
    description: Send a private message to a player
  mutechat:
    usage: /mutechat
    description: Mute the chat (ADMIN ONLY)
  sethealth:
    usage: /sethealth <player> <health>
    description: Set a players health (ADMIN ONLY)
  clearchat:
    usage: /clearchat
    description: Clear the chat
  plugins:
    usage: /plugins
    description: yes
    aliases:
      - pl
  help:
    usage: /help
    description: yes
    aliases:
      - ?