name: Lifesteal
version: '${project.version}'
main: net.meadownetwork.lifesteal.main
api-version: 1.18
authors: [ Banker ]
commands:
  resethealth:
    usage: /resethealth
    description: Reset your max health to the default value of 20
    permission: lifesteal.resethealth
  gm:
    usage: /gm
    description: Toggle your gamemode
    permission: lifesteal.gamemode
  fly:
    usage: /fly
    description: Toggle your fly mode
    permission: lifesteal.fly
  report:
    usage: /report <player>
    description: Report a player to the server staff
  rtp:
    usage: /rtp <player>
    description: Randomly teleport to a random possible location
    permission: lifesteal.rtp
  customheartgiver:
    usage: /customheartgiver
    description: Give you a heart item
    permission: lifesteal.heartitemgiver
  maintenancemode:
    usage: /maintenancemode
    description: Toggle maintenance mode
    permission: lifesteal.maintenancemode
  crategive:
    usage: /givecrate
    description: Give you a crate
    permission: lifesteal.crategive